

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function FormLayout({ children }) {
  return (
      <main className="grid place-content-center min-h-screen">{children}</main>
  )
}
