import Nav from './components/Nav'
import { AppWrapper } from './components/States'
import './globals.css'
import { Poppins } from 'next/font/google'

const poppins = Poppins({ subsets: ['devanagari'], weight: '400' })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} bg-black text-white`}>
        <AppWrapper>
        <Nav />
        {children}
        </AppWrapper>
        </body>
    </html>
  )
}
