

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function SignupLayout({ children }) {
  return (
      <main className="grid min-h-screen">{children}</main>
  )
}
